name: main

on:
  # Cho phép chạy bằng tay từ giao diện Github
  workflow_dispatch:
  # Lên lịch chạy hàng ngày vào lúc 00:00 UTC
  schedule:
  - cron: "0 0,8,12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Update and reinstall CA certificates
        run: |
          sudo apt update
          sudo apt install --reinstall ca-certificates

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        # Khởi tạo môi trường NodeJS
        with:
          node-version: 16

      - run: npm ci

      - name: Generate quote
        # Chạy script để gọi API lấy quote sau đó sửa file README.md
        run: npm run generate

      - name: Update README.md
        # Push file README.md đã được thay đổi lên github
        run: |
          git config --global user.email "bthanhtung.se@gmail.com"
          git config --global user.name "bthanhtung"
          git fetch origin
          git pull origin master
          git add .
          git commit -m "Updated README.md" || echo "No changes to commit"
          git push origin master
