# # This is a basic workflow to help you get started with Actions

# name: CI

# # Controls when the action will run. 
# on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

#   # Allows you to run this workflow manually from the Actions tab
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       # Runs a single command using the runners shell
#       - name: Run a one-line script
#         run: echo Hello, world!

#       # Runs a set of commands using the runners shell
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
name: main

on:
  # Cho phép chạy bằng tay từ giao diện Github
  workflow_dispatch:
  # Lên lịch chạy hàng ngày vào lúc 00:00 UTC
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      # Khởi tạo môi trường NodeJS
      with:
        node-version: 12.16.1
    - run: npm ci
    - name: Generate quote
      # Chạy script để gọi API lấy quote sau đó sửa file README.md
      run: npm run generate
    - name: Update README.md
      # Push file README.md đã được thay đổi lên github
      run: |
        git config --global user.email "bthanhtung.se@gmail.com"
        git config --global user.name "bthanhtung"
        git add .
        git commit -m "Updated README.md" || echo "No changes to commit"
        git push
